INSERT INTO Teacher (ID, Name, Qualification)
VALUES
  (1, 'Dr. Johnson', 'PhD in Mathematics'),
  (2, 'Prof. Anderson', 'Masters in Physics'),
  (3, 'Ms. Garcia', 'Bachelor in Chemistry'),
  (4, 'Mr. Smith', 'PhD in Biology'),
  (5, 'Dr. Brown', 'Masters in Statistics'),
  (6, 'Mrs. Taylor', 'PhD in Computer Science'),
  (7, 'Ms. Lee', 'Masters in Education'),
  (8, 'Mr. Clark', 'PhD in History'),
  (9, 'Dr. Martinez', 'Masters in Economics'),
  (10, 'Prof. Wright', 'PhD in Engineering'),
  (11, 'Ms. Hall', 'Masters in English'),
  (12, 'Mr. Adams', 'PhD in Sociology'),
  (13, 'Dr. Rodriguez', 'Masters in Psychology'),
  (14, 'Ms. Harris', 'PhD in Philosophy'),
  (15, 'Prof. Gonzalez', 'Masters in Fine Arts'),
  (16, 'Dr. Scott', 'PhD in Political Science'),
  (17, 'Mr. King', 'Masters in Linguistics'),
  (18, 'Prof. Green', 'PhD in Environmental Science'),
  (19, 'Dr. Carter', 'Masters in Business Administration'),
  (20, 'Ms. Parker', 'PhD in Anthropology'),
  (21, 'Prof. Lewis', 'Masters in Music'),
  (22, 'Dr. Turner', 'PhD in Geology'),
  (23, 'Mr. Stewart', 'Masters in Public Health'),
  (24, 'Prof. Powell', 'PhD in Philosophy'),
  (25, 'Dr. Cooper', 'Masters in Nursing'),
  (26, 'Ms. Evans', 'PhD in Nutrition'),
  (27, 'Prof. Barnes', 'Masters in Drama'),
  (28, 'Dr. Perez', 'PhD in Social Work'),
  (29, 'Mr. Morris', 'Masters in Theology'),
  (30, 'Prof. Ramirez', 'PhD in Religious Studies'),
  (31, 'Dr. Flores', 'Masters in Physical Therapy'),
  (32, 'Ms. Richardson', 'PhD in Kinesiology'),
  (33, 'Prof. Jenkins', 'Masters in Film Studies'),
  (34, 'Dr. Ward', 'PhD in Dentistry'),
  (35, 'Ms. Bell', 'Masters in Pharmacy'),
  (36, 'Prof. Collins', 'PhD in Veterinary Medicine'),
  (37, 'Dr. Butler', 'Masters in Aerospace Engineering'),
  (38, 'Mr. Fisher', 'PhD in Agriculture'),
  (39, 'Prof. Long', 'Masters in Forestry'),
  (40, 'Dr. Powell', 'PhD in Mathematics'),
  (41, 'Ms. Garcia', 'Masters in Physics'),
  (42, 'Prof. Adams', 'PhD in Chemistry'),
  (43, 'Dr. Smith', 'Masters in Biology'),
  (44, 'Ms. Johnson', 'PhD in Statistics'),
  (45, 'Prof. Brown', 'Masters in Computer Science'),
  (46, 'Dr. Taylor', 'PhD in History'),
  (47, 'Mr. Martinez', 'Masters in Economics'),
  (48, 'Prof. Wright', 'PhD in Engineering'),
  (49, 'Ms. Hall', 'Masters in English'),
  (50, 'Dr. Adams', 'PhD in Sociology'),
  (51, 'Mr. Rodriguez', 'Masters in Psychology'),
  (52, 'Prof. Harris', 'PhD in Philosophy'),
  (53, 'Dr. Gonzalez', 'Masters in Fine Arts'),
  (54, 'Ms. Scott', 'PhD in Political Science'),
  (55, 'Prof. King', 'Masters in Linguistics'),
  (56, 'Dr. Green', 'PhD in Environmental Science'),
  (57, 'Mr. Carter', 'Masters in Business Administration'),
  (58, 'Prof. Parker', 'PhD in Anthropology'),
  (59, 'Dr. Lewis', 'Masters in Music'),
  (60, 'Ms. Turner', 'PhD in Geology'),
  (61, 'Prof. Stewart', 'Masters in Public Health'),
  (62, 'Dr. Powell', 'PhD in Philosophy'),
  (63, 'Mr. Cooper', 'Masters in Nursing'),
  (64, 'Prof. Evans', 'PhD in Nutrition'),
  (65, 'Dr. Barnes', 'Masters in Drama'),
  (66, 'Ms. Perez', 'PhD in Social Work'),
  (67, 'Prof. Morris', 'Masters in Theology'),
  (68, 'Dr. Ramirez', 'PhD in Religious Studies'),
  (69, 'Mr. Flores', 'Masters in Physical Therapy'),
  (70, 'Prof. Richardson', 'PhD in Kinesiology'),
  (71, 'Dr. Jenkins', 'Masters in Film Studies'),
  (72, 'Ms. Ward', 'PhD in Dentistry'),
  (73, 'Prof. Bell', 'Masters in Pharmacy'),
  (74, 'Dr. Collins', 'PhD in Veterinary Medicine'),
  (75, 'Mr. Butler', 'Masters in Aerospace Engineering'),
  (76, 'Prof. Fisher', 'PhD in Agriculture'),
  (77, 'Dr. Long', 'Masters in Forestry'),
  (78, 'Ms. Powell', 'PhD in Mathematics'),
  (79, 'Prof. Garcia', 'Masters in Physics'),
  (80, 'Dr. Adams', 'PhD in Chemistry'),
  (81, 'Mr. Smith', 'Masters in Biology'),
  (82, 'Prof. Johnson', 'PhD in Statistics'),
  (83, 'Dr. Brown', 'Masters in Computer Science'),
  (84, 'Ms. Taylor', 'PhD in History'),
  (85, 'Prof. Martinez', 'Masters in Economics'),
  (86, 'Dr. Wright', 'PhD in Engineering'),
  (87, 'Mr. Hall', 'Masters in English'),
  (88, 'Prof. Adams', 'PhD in Sociology'),
  (89, 'Dr. Rodriguez', 'Masters in Psychology'),
  (90, 'Ms. Harris', 'PhD in Philosophy'),
  (91, 'Prof. Gonzalez', 'Masters in Fine Arts'),
  (92, 'Dr. Scott', 'PhD in Political Science'),
  (93, 'Mr. King', 'Masters in Linguistics'),
  (94, 'Prof. Green', 'PhD in Environmental Science'),
  (95, 'Dr. Carter', 'Masters in Business Administration'),
  (96, 'Ms. Parker', 'PhD in Anthropology'),
  (97, 'Prof. Lewis', 'Masters in Music'),
  (98, 'Dr. Turner', 'PhD in Geology'),
  (99, 'Mr. Stewart', 'Masters in Public Health'),
  (100, 'Prof. Powell', 'PhD in Philosophy');